name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Git identity
        run: |
          git config --global user.email "sefabuyukdikmen@gmail.com"
          git config --global user.name "sefabydkm"

      - name: Install dependencies
        run: npm install

      - name: Build and Deploy
        run: npm run deploy